# mariadbver: 10.4      # 10.1 10.2 10.3 10.4
# mongodb_ver: 4.0    # 默认版本  3.0  3.2 3.4 3.6  4.0 
# mysqlver: 5.6       # centos版本 5.5 5.6 5.7  Ubuntu支持5.7和8.0
# nodejs_ver: 10  # 默认版本10  8 10 11 13
# phpver: 7.2   # 默认版本7.2  5.6 7.0 7.1 7.2 7.3
# postgresqlver: 9.5     # 9.4 9.5 9.6 10 11 
# redis_ver: stable #默认版本 stable  全版本支持 版本信息查看http://download.redis.io/releases/




# 额外数据库相关,
# app_db: ansible
# app_db_user: ansible
# app_db_password: password
# app_db_host: 127.0.0.1

# db_service_name: mysqld

# 数据库连接配置文件路径X
# db_config_path:
#   - /root/1
#   - /root/2
