---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Creates awx dock directory
  file:
    path: /data/.awx/redis_socket
    state: directory
    recurse: yes

- name: Copy docker env
  template:
    src: "{{item}}"
    dest: '/data/.awx'
  loop:
    - credentials.py
    - docker-compose.yml
    - environment.sh
    - nginx.conf
    - redis.conf
    - SECRET_KEY
    
- name: Create awx softlink to /data/wwwroot/awx
  file:
    src: /data/.awx
    dest: /data/wwwroot/awx
    state: link
    
- name: Run docker-compose
  shell: |
    docker-compose up -d 
    sleep 30s
  args:
    chdir: /data/.awx
