version: '2'
services:

  web:
    image: ansible/awx:{{awx_version}}
    container_name: awx_web
    depends_on:
      - redis
    ports:
      - "{{awx_http_port}}:8052"
      - "443:443"
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - /data/cert:/etc/ssl/certs
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "/data/.awx/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "/data/.awx/environment.sh:/etc/tower/conf.d/environment.sh"
      - "/data/.awx/credentials.py:/etc/tower/conf.d/credentials.py"
      - "/data/.awx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/data/.awx/redis_socket:/var/run/redis/:rw"
      - "/data/.awx/projects:/var/lib/awx/projects:rw"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 

  task:
    image: ansible/awx:{{awx_version}}
    container_name: awx_task
    depends_on:
      - redis
      - web   
    command: /usr/bin/launch_awx_task.sh
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "/data/.awx/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "/data/.awx/environment.sh:/etc/tower/conf.d/environment.sh"
      - "/data/.awx/credentials.py:/etc/tower/conf.d/credentials.py"
      - "/data/.awx/redis_socket:/var/run/redis/:rw"
      - "/data/.awx/projects:/var/lib/awx/projects:rw"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
      SUPERVISOR_WEB_CONFIG_PATH: '/etc/supervisord.conf'

  redis:
    image: redis
    container_name: awx_redis
    restart: unless-stopped
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - "/data/.awx/redis.conf:/usr/local/etc/redis/redis.conf:ro"
      - "/data/.awx/redis_socket:/var/run/redis/:rw"

volumes:
  supervisor-socket:
  rsyslog-socket:
  rsyslog-config:
