  # Centos 
- block:
  - name: Install required packages
    yum:
      name: [yum-utils,device-mapper-persistent-data,lvm2]

  - name: Add repository
    template:
      src: docker.repo.jinja2
      dest: /etc/yum.repos.d/docker.repo
        
  - name: Install Docker
    yum:
      name: [docker-ce,docker-ce-cli,containerd.io]
    
  when: ansible_distribution == 'CentOS'

  # # Ubuntu
- block:
  - name: Install required packages
    apt:
      name: [apt-transport-https,ca-certificates,curl,gnupg-agent,software-properties-common,python-pip,python-setuptools]
    

  - name:  Add Dockerâ€™s official GPG key
    apt_key:
      url:  https://download.docker.com/linux/ubuntu/gpg
      id: 0EBFCD88

  - name: Add repository 
    apt_repository:
      filename: docker
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable
      
  - name: Install Docker
    apt:
      name: [docker-ce,docker-ce-cli,containerd.io]
        
  when: ansible_distribution == 'Ubuntu'

- name: pip requirements
  pip:
    name: [docker]

- name: Started Docker
  service:
    name: docker 
    enabled: yes
    state: restarted
      
- name: Check Docker Version
  shell: docker -v
  register: docker_ver
  notify: Docker Version
